CREATE TABLE IF NOT EXISTS convenios
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa VARCHAR(100) NOT NULL,
    cnpj VARCHAR(20) NOT NULL,
    telefone VARCHAR(15) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_swedish_ci;